"""adding a password column

Revision ID: 53b51c9fbb27
Revises: 7efbbdc2c0e0
Create Date: 2026-05-07 23:04:37.620912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "53b51c9fbb27"
down_revision: Union[str, Sequence[str], None] = "7efbbdc2c0e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=200), nullable=True)
    )

    ## add a default password for the existing users
    import bcrypt

    password_bytes = b"snippets"
    salt = bcrypt.gensalt()
    hashed_bytes = bcrypt.hashpw(password_bytes, salt)
    default_password_hash = hashed_bytes.decode("utf-8")

    # Run an UPDATE query to give all existing users this default hashed password
    op.execute(
        f"UPDATE users SET hashed_password = '{default_password_hash}' WHERE hashed_password IS NULL"
    )

    # op.alter_column("users", "hashed_password", nullable=False)

    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("hashed_password", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
